name: CPlotRedstoneCircuitIntegration
main: ColinHDev\CPlotRedstoneCircuitIntegration\CPlotRedstoneCircuitIntegration
version: "1.0.0"
description: "CPlot addon for integrating the RedstoneCircuit plugin into plot worlds"

api: 4.0.0
depend:
- CPlot
- RedstoneCircuit

author: ColinHDev
website: https://github.com/ColinHDev